name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Restore
        run: dotnet restore .\MultiWebView\MultiWebView.csproj

      - name: Build
        run: dotnet build .\MultiWebView\MultiWebView.csproj --configuration Release --no-restore
